import XCTest
@testable import DS4Core

final class DeepSeek41EngramTests: XCTestCase {
    private func layout() throws -> DeepSeek41Engram.Layout {
        try .init(tokenMap: [2, 0, 1, 4, 3], compressedVocabulary: 5, padID: 4,
                  rows: [72, 120], multipliers: [[1, 3, 5, 7], [9, 11, 13, 15]],
                  primes: [Array(repeating: 3, count: 24), Array(repeating: 5, count: 24)])
    }
    func testHashMatchesPinnedCAndIncrementalMaskedHistory() throws {
        let layout = try layout()
        var history: [Int32] = [-1, -1, -1]
        let batch = try layout.hash(tokens: [0, 2, 3, 1], mask: [true, true, false, true], history: &history)
        // Golden generated by ds4_engram.c at acf5c16, not by Swift hash code.
        XCTAssertEqual((0..<4).map { batch[0][$0 * 24] }, [2, 1, 2, 0])
        XCTAssertEqual((0..<4).map { batch[1][$0 * 24] }, [2, 1, 3, 4])
        XCTAssertEqual(history, [0, -1, 1])
        var incrementalHistory: [Int32] = [-1, -1, -1]
        let prefix = try layout.hash(tokens: [0, 2], history: &incrementalHistory)
        let suffix = try layout.hash(tokens: [3, 1], mask: [false, true], history: &incrementalHistory)
        XCTAssertEqual(batch, zip(prefix, suffix).map(+))
        XCTAssertEqual(incrementalHistory, history)
        let saved = history
        XCTAssertThrowsError(try layout.hash(tokens: [0, 5], history: &history))
        XCTAssertEqual(history, saved, "Validate whole input before mutation")
    }
    func testLayoutRejectsOverflowAndBadPrimeSum() throws {
        XCTAssertThrowsError(try DeepSeek41Engram.Layout(tokenMap: [0], compressedVocabulary: 5, padID: 4, rows: [72,120], multipliers: [[UInt64.max,3,5,7],[9,11,13,15]], primes: [Array(repeating: 3, count: 24),Array(repeating: 5, count: 24)]))
        XCTAssertThrowsError(try DeepSeek41Engram.Layout(tokenMap: [5], compressedVocabulary: 5, padID: 4, rows: [72,120], multipliers: [[1,3,5,7],[9,11,13,15]], primes: [Array(repeating: 3, count: 24),Array(repeating: 5, count: 24)]))
    }
    func testOriginalFP8RowsReadFromSSDAndBounds() throws {
        var row = [UInt8](repeating: 0, count: 264)
        for i in 0..<256 { row[i] = UInt8(i % 127) }
        for i in 256..<264 { row[i] = 127 }
        row[0] = 56; row[1] = 184; row[2] = 1; row[3] = 126
        let decoded = try DeepSeek41Engram.Table.decode(row: row)
        XCTAssertEqual(Array(decoded.prefix(4)), [1, -1, 1.0 / 512, 448])
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: url) }
        try Data([UInt8](repeating: 0, count: 64) + row + row).write(to: url)
        let table = try DeepSeek41Engram.Table(path: url.path, offset: 64, rows: 2)
        XCTAssertEqual(try table.read(rows: [1,0,1]), decoded + decoded + decoded)
        XCTAssertThrowsError(try table.read(rows: [2]))
        XCTAssertThrowsError(try DeepSeek41Engram.Table(path: url.path, offset: 65, rows: 2))
        XCTAssertThrowsError(try DeepSeek41Engram.Table(path: url.path, offset: UInt64.max, rows: 2))
        row[0] = 127
        XCTAssertThrowsError(try DeepSeek41Engram.Table.decode(row: row))
        row[0] = 56; row[256] = 255
        XCTAssertThrowsError(try DeepSeek41Engram.Table.decode(row: row))
    }
}
