/*
 * Fixture generator: encodes deterministic inputs with the ds4 reference
 * quantizers (quants.c, compiled with -ffp-contract=off) and emits a Swift
 * file with the input bit patterns and expected output bytes.
 */
#include "quants.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>

static uint32_t rng_state = 0x12345678u;
static uint32_t xorshift32(void) {
    uint32_t x = rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    rng_state = x;
    return x;
}
/* Uniform in [-1, 1), deterministic across platforms. */
static float rng_float(void) {
    return ((float)(xorshift32() >> 8) / 8388608.0f) * 2.0f - 1.0f;
}

#define NINPUT 1024
#define NIMATRIX 512

static float input[NINPUT];
static float imatrix[NIMATRIX];

static void build_inputs(void) {
    /* Crafted first 256-block: zeros, constants, spikes, alternating. */
    for (int i = 0; i < 64; i++) input[i] = 0.0f;               /* zeros   */
    for (int i = 64; i < 128; i++) input[i] = 0.5f;             /* constant*/
    for (int i = 128; i < 192; i++) input[i] = (i % 7 == 0) ? -3.0f : 0.01f;
    for (int i = 192; i < 256; i++) input[i] = (i % 2 == 0) ? 1.0f : -1.0f;
    for (int i = 256; i < NINPUT; i++) input[i] = rng_float() * 2.5f;
    for (int i = 0; i < NIMATRIX; i++) {
        float v = rng_float();
        imatrix[i] = 0.05f + v * v;   /* strictly positive importance */
    }
}

static void emit_u32_array(FILE *f, const char *name, const float *v, int n) {
    fprintf(f, "    static let %s: [UInt32] = [\n        ", name);
    for (int i = 0; i < n; i++) {
        uint32_t bits;
        memcpy(&bits, &v[i], 4);
        fprintf(f, "0x%08x,%s", bits, (i % 8 == 7) ? "\n        " : " ");
    }
    fprintf(f, "\n    ]\n");
}

static void emit_u8_array(FILE *f, const char *name, const uint8_t *v, size_t n) {
    fprintf(f, "    static let %s: [UInt8] = [\n        ", name);
    for (size_t i = 0; i < n; i++) {
        fprintf(f, "0x%02x,%s", v[i], (i % 16 == 15) ? "\n        " : " ");
    }
    fprintf(f, "\n    ]\n");
}

int main(void) {
    build_inputs();
    static uint8_t out[1 << 16];
    FILE *f = fopen("QuantEncodeFixtures.swift", "w");
    if (!f) return 1;

    fprintf(f, "// GENERATED by scratchpad fixture_gen.c from ds4 gguf-tools/quants.c\n");
    fprintf(f, "// (clang -O2 -ffp-contract=off). Do not edit by hand: inputs are the\n");
    fprintf(f, "// crafted+xorshift32(0x12345678) stream, outputs are the reference bytes.\n");
    fprintf(f, "enum QuantEncodeFixtures {\n");
    emit_u32_array(f, "inputBits", input, NINPUT);
    emit_u32_array(f, "imatrixBits", imatrix, NIMATRIX);

    size_t n;

    /* q8_0: 2 rows x 64 columns over the first 128 values. */
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q8_0, input, out, 0, 2, 64, NULL);
    emit_u8_array(f, "q8_0", out, n);

    /* q8_K: 2 rows x 512. */
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q8_K, input, out, 0, 2, 512, NULL);
    emit_u8_array(f, "q8_K", out, n);

    /* q4_K ref + weighted: 2 rows x 512. */
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q4_K, input, out, 0, 2, 512, NULL);
    emit_u8_array(f, "q4_K_ref", out, n);
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q4_K, input, out, 0, 2, 512, imatrix);
    emit_u8_array(f, "q4_K_weighted", out, n);

    /* q2_K ref + weighted: 2 rows x 512. */
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q2_K, input, out, 0, 2, 512, NULL);
    emit_u8_array(f, "q2_K_ref", out, n);
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q2_K, input, out, 0, 2, 512, imatrix);
    emit_u8_array(f, "q2_K_weighted", out, n);

    /* iq2_xxs: 2 rows x 512, imatrix required. */
    memset(out, 0, sizeof(out));
    ds4q_quantize_init(DS4Q_TYPE_IQ2_XXS);
    n = ds4q_quantize_chunk(DS4Q_TYPE_IQ2_XXS, input, out, 0, 2, 512, imatrix);
    emit_u8_array(f, "iq2_xxs", out, n);

    /* Second-row start offset: quantize only row 1 of the q8_0 layout to pin
     * the `start` offset math. */
    memset(out, 0, sizeof(out));
    n = ds4q_quantize_chunk(DS4Q_TYPE_Q8_0, input, out, 64, 1, 64, NULL);
    emit_u8_array(f, "q8_0_row1", out, 64 / 32 * 34 * 2);

    fprintf(f, "}\n");
    fclose(f);
    fprintf(stderr, "fixtures written\n");
    return 0;
}
