// Generated by scripts/embed_backend_kernels.py; edit metal/ sources.
enum GLM53KernelSources {
    static let all: [String] = [
####"""
// Ported from GiorgioOppo/ds4 acf5c16bb6a01f8c4f027a0db265ae270d8907ab.
// MIT license; see metal/glm53/LICENSE and the upstream LICENSE.
// BF16 model-weight kernels used by GLM-5.3 Flash.

static inline float glm53_bf16_to_f32(ushort value) {
    return as_type<float>((uint)value << 16);
}

struct glm53_bf16_matmul_args {
    uint in_dim;
    uint out_dim;
    uint n_rows;
};

kernel void kernel_glm53_embedding_bf16(
        constant glm53_bf16_matmul_args &args,
        device const ushort             *weights,
        device const int                *tokens,
        device float                    *out,
        uint2 gid [[thread_position_in_grid]]) {
    const uint d = gid.x;
    const uint row = gid.y;
    if (d >= args.in_dim || row >= args.n_rows) return;
    const int token = tokens[row];
    out[(ulong)row * args.in_dim + d] =
        token >= 0 && (uint)token < args.out_dim
            ? glm53_bf16_to_f32(weights[(ulong)(uint)token * args.in_dim + d])
            : 0.0f;
}

static inline void glm53_mul_mv_bf16_f32_row(
        constant glm53_bf16_matmul_args &args,
        device const ushort             *weights,
        device const float              *x,
        device float                    *out,
        uint2                            tgpig,
        ushort                           lane,
        ushort                           sg,
        ushort                           nsg) {
    const uint out_row = tgpig.x * (uint)nsg + sg;
    const uint token = tgpig.y;
    if (out_row >= args.out_dim || token >= args.n_rows) return;

    device const ushort *w = weights + (ulong)out_row * args.in_dim;
    device const float *xr = x + (ulong)token * args.in_dim;
    float sum = 0.0f;
    uint k = lane;
    for (; k + 224u < args.in_dim; k += 256u) {
        const ushort w0 = w[k];
        const ushort w1 = w[k + 32u];
        const ushort w2 = w[k + 64u];
        const ushort w3 = w[k + 96u];
        const ushort w4 = w[k + 128u];
        const ushort w5 = w[k + 160u];
        const ushort w6 = w[k + 192u];
        const ushort w7 = w[k + 224u];
        const float x0 = xr[k];
        const float x1 = xr[k + 32u];
        const float x2 = xr[k + 64u];
        const float x3 = xr[k + 96u];
        const float x4 = xr[k + 128u];
        const float x5 = xr[k + 160u];
        const float x6 = xr[k + 192u];
        const float x7 = xr[k + 224u];
        sum = fma(glm53_bf16_to_f32(w0), x0, sum);
        sum = fma(glm53_bf16_to_f32(w1), x1, sum);
        sum = fma(glm53_bf16_to_f32(w2), x2, sum);
        sum = fma(glm53_bf16_to_f32(w3), x3, sum);
        sum = fma(glm53_bf16_to_f32(w4), x4, sum);
        sum = fma(glm53_bf16_to_f32(w5), x5, sum);
        sum = fma(glm53_bf16_to_f32(w6), x6, sum);
        sum = fma(glm53_bf16_to_f32(w7), x7, sum);
    }
    for (; k < args.in_dim; k += 32u) {
        sum = fma(glm53_bf16_to_f32(w[k]), xr[k], sum);
    }
    sum = simd_sum(sum);
    if (lane == 0u) out[(ulong)token * args.out_dim + out_row] = sum;
}

/* One simdgroup owns one output row. Eight independent loads expose enough
 * memory-level parallelism for decode without changing the reduction tree. */
kernel void kernel_glm53_mul_mv_bf16_f32(
        constant glm53_bf16_matmul_args &args,
        device const ushort             *weights,
        device const float              *x,
        device float                    *out,
        uint2 tgpig [[threadgroup_position_in_grid]],
        ushort lane [[thread_index_in_simdgroup]],
        ushort sg [[simdgroup_index_in_threadgroup]],
        ushort nsg [[simdgroups_per_threadgroup]]) {
    glm53_mul_mv_bf16_f32_row(args, weights, x, out,
                              tgpig, lane, sg, nsg);
}

kernel void kernel_glm53_mul_mv_bf16_f32_qkv(
        constant glm53_bf16_matmul_args &args,
        device const ushort             *weights_q,
        device const ushort             *weights_k,
        device const ushort             *weights_v,
        device const float              *x,
        device float                    *out_q,
        device float                    *out_k,
        device float                    *out_v,
        uint3 tgpig [[threadgroup_position_in_grid]],
        ushort lane [[thread_index_in_simdgroup]],
        ushort sg [[simdgroup_index_in_threadgroup]],
        ushort nsg [[simdgroups_per_threadgroup]]) {
    device const ushort *weights = tgpig.z == 0u ? weights_q :
                                     (tgpig.z == 1u ? weights_k : weights_v);
    device float *out = tgpig.z == 0u ? out_q :
                            (tgpig.z == 1u ? out_k : out_v);
    glm53_mul_mv_bf16_f32_row(args, weights, x, out,
                              tgpig.xy, lane, sg, nsg);
}

struct glm53_bf16_block16 {
    ushort v[16];
};

template <typename type4x4>
void glm53_dequantize_bf16(
        device const glm53_bf16_block16 *src,
        short il,
        thread type4x4 &reg) {
    (void)il;
    float4x4 values;
    for (short i = 0; i < 16; i++) {
        values[i / 4][i % 4] = glm53_bf16_to_f32(src->v[i]);
    }
    reg = (type4x4)values;
}

typedef decltype(kernel_mul_mm<
        half, half4x4, simdgroup_half8x8,
        half, half2x4, simdgroup_half8x8,
        glm53_bf16_block16, 1, glm53_dequantize_bf16,
        float, float4x4, float, float2x4>) glm53_mul_mm_bf16_t;

template [[host_name("kernel_glm53_mul_mm_bf16_f32")]]
kernel glm53_mul_mm_bf16_t kernel_mul_mm<
        half, half4x4, simdgroup_half8x8,
        half, half2x4, simdgroup_half8x8,
        glm53_bf16_block16, 1, glm53_dequantize_bf16,
        half, half4x4, float, float2x4>;
"""####,
####"""
// Ported from GiorgioOppo/ds4 acf5c16bb6a01f8c4f027a0db265ae270d8907ab.
// MIT license; see metal/glm53/LICENSE and the upstream LICENSE.
// Kimi Delta Attention kernels, adapted from the kimi-k3 branch.

struct glm53_kda_args {
    uint n_heads;
    uint n_rows;
    float lower_bound;
    float norm_eps;
};

/*
 * One threadgroup owns one (sequence, head). Four simdgroups update four
 * value rows concurrently; every lane owns four adjacent key columns.
 */
kernel void kernel_glm53_kda_decode(
        constant glm53_kda_args &args,
        device const float   *q_in,
        device const float   *k_in,
        device const float   *v_in,
        device const float   *raw_gate,
        device const float   *raw_beta,
        device const float   *output_gate,
        device const float   *q_conv,
        device const float   *k_conv,
        device const float   *v_conv,
        device const float   *a_log,
        device const float   *dt_bias,
        device const float   *output_norm,
        device float         *conv_state,
        device float         *state,
        device float         *out,
        threadgroup float    *scratch [[threadgroup(0)]],
        uint2 tgpig [[threadgroup_position_in_grid]],
        ushort tid [[thread_index_in_threadgroup]],
        ushort lane [[thread_index_in_simdgroup]],
        ushort sg [[simdgroup_index_in_threadgroup]]) {
    constexpr uint D = 128u;
    constexpr uint HISTORY = 3u;
    const uint row = tgpig.x;
    const uint head = tgpig.y;
    if (row >= args.n_rows || head >= args.n_heads) return;

    threadgroup float *sq = scratch;
    threadgroup float *sk = sq + D;
    threadgroup float *sd = sk + D;
    threadgroup float *sv = sd + D;
    threadgroup float *so = sv + D;
    threadgroup float *reduce_q = so + D;
    threadgroup float *reduce_k = reduce_q + 4u;
    threadgroup float *reduce_o = reduce_k + 4u;
    threadgroup float *beta_shared = reduce_o + 4u;

    const uint projection = args.n_heads * D;
    const uint channel = head * D + tid;
    const ulong input_base = (ulong)row * projection + head * D;
    const ulong conv_row_stride = 3ul * HISTORY * projection;

    if (tid < D) {
        float q_acc = 0.0f;
        float k_acc = 0.0f;
        float v_acc = 0.0f;
        device float *q_state = conv_state +
            (ulong)row * conv_row_stride;
        device float *k_state = q_state + HISTORY * projection;
        device float *v_state = k_state + HISTORY * projection;
        for (uint w = 0; w < HISTORY; w++) {
            q_acc = fma(q_state[(ulong)w * projection + channel],
                        q_conv[(ulong)channel * 4u + w], q_acc);
            k_acc = fma(k_state[(ulong)w * projection + channel],
                        k_conv[(ulong)channel * 4u + w], k_acc);
            v_acc = fma(v_state[(ulong)w * projection + channel],
                        v_conv[(ulong)channel * 4u + w], v_acc);
        }
        const float q_new = q_in[input_base + tid];
        const float k_new = k_in[input_base + tid];
        const float v_new = v_in[input_base + tid];
        q_acc = fma(q_new, q_conv[(ulong)channel * 4u + 3u], q_acc);
        k_acc = fma(k_new, k_conv[(ulong)channel * 4u + 3u], k_acc);
        v_acc = fma(v_new, v_conv[(ulong)channel * 4u + 3u], v_acc);

        q_state[channel] = q_state[projection + channel];
        q_state[projection + channel] = q_state[2ul * projection + channel];
        q_state[2ul * projection + channel] = q_new;
        k_state[channel] = k_state[projection + channel];
        k_state[projection + channel] = k_state[2ul * projection + channel];
        k_state[2ul * projection + channel] = k_new;
        v_state[channel] = v_state[projection + channel];
        v_state[projection + channel] = v_state[2ul * projection + channel];
        v_state[2ul * projection + channel] = v_new;

        sq[tid] = q_acc / (1.0f + exp(-q_acc));
        sk[tid] = k_acc / (1.0f + exp(-k_acc));
        sv[tid] = v_acc / (1.0f + exp(-v_acc));
        const float gate = raw_gate[input_base + tid] + dt_bias[channel];
        sd[tid] = exp(args.lower_bound *
                      (1.0f / (1.0f + exp(-exp(a_log[head]) * gate))));
    }
    if (tid == 0u) {
        beta_shared[0] =
            1.0f / (1.0f + exp(-raw_beta[(ulong)row * args.n_heads + head]));
    }
    threadgroup_barrier(mem_flags::mem_threadgroup |
                       mem_flags::mem_device);

    float q_sumsq = sq[tid] * sq[tid];
    float k_sumsq = sk[tid] * sk[tid];
    q_sumsq = simd_sum(q_sumsq);
    k_sumsq = simd_sum(k_sumsq);
    if (lane == 0u) {
        reduce_q[sg] = q_sumsq;
        reduce_k[sg] = k_sumsq;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float q_total = lane < 4u ? reduce_q[lane] : 0.0f;
    float k_total = lane < 4u ? reduce_k[lane] : 0.0f;
    q_total = simd_sum(q_total);
    k_total = simd_sum(k_total);
    const float q_scale = rsqrt(q_total + 1.0e-6f) * 0x1.6a09e6p-4f;
    const float k_scale = rsqrt(k_total + 1.0e-6f);
    if (tid < D) {
        sq[tid] *= q_scale;
        sk[tid] *= k_scale;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    const uint k0 = lane * 4u;
    const float4 q4 = *((threadgroup float4 *)(sq + k0));
    const float4 k4 = *((threadgroup float4 *)(sk + k0));
    const float4 decay4 = *((threadgroup float4 *)(sd + k0));
    const ulong state_head =
        ((ulong)row * args.n_heads + head) * D * D;

    for (uint value = sg; value < D; value += 4u) {
        device float4 *hptr =
            (device float4 *)(state + state_head + (ulong)value * D + k0);
        float4 h = *hptr * decay4;
        float hk = dot(h, k4);
        hk = simd_sum(hk);
        const float delta_v = (sv[value] - hk) * beta_shared[0];
        h = fma(k4, float4(delta_v), h);
        *hptr = h;
        float hq = simd_sum(dot(h, q4));
        if (lane == 0u) so[value] = hq;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup |
                       mem_flags::mem_device);

    float o_sumsq = so[tid] * so[tid];
    o_sumsq = simd_sum(o_sumsq);
    if (lane == 0u) reduce_o[sg] = o_sumsq;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float o_total = lane < 4u ? reduce_o[lane] : 0.0f;
    o_total = simd_sum(o_total);
    const float o_scale = rsqrt(o_total / (float)D + args.norm_eps);
    if (tid < D) {
        const ulong index = input_base + tid;
        const float gate =
            1.0f / (1.0f + exp(-output_gate[index]));
        out[index] = so[tid] * o_scale * output_norm[tid] * gate;
    }
}

kernel void kernel_glm53_kda_prefill_prepare(
        constant glm53_kda_args &args,
        device float         *q,
        device float         *k,
        device float         *v,
        device float         *raw_gate,
        device const float   *q_conv,
        device const float   *k_conv,
        device const float   *v_conv,
        device const float   *a_log,
        device const float   *dt_bias,
        device float         *conv_state,
        threadgroup float    *scratch [[threadgroup(0)]],
        uint head [[threadgroup_position_in_grid]],
        ushort tid [[thread_index_in_threadgroup]],
        ushort lane [[thread_index_in_simdgroup]],
        ushort sg [[simdgroup_index_in_threadgroup]]) {
    constexpr uint D = 128u;
    constexpr uint HISTORY = 3u;
    if (head >= args.n_heads) return;
    threadgroup float *sq = scratch;
    threadgroup float *sk = sq + D;
    threadgroup float *reduce_q = sk + D;
    threadgroup float *reduce_k = reduce_q + 4u;
    const uint projection = args.n_heads * D;
    const uint channel = head * D + tid;
    device float *q_state = conv_state;
    device float *k_state = q_state + HISTORY * projection;
    device float *v_state = k_state + HISTORY * projection;

    for (uint token = 0; token < args.n_rows; token++) {
        const ulong index = (ulong)token * projection + channel;
        float q_acc = 0.0f;
        float k_acc = 0.0f;
        float v_acc = 0.0f;
        for (uint w = 0; w < HISTORY; w++) {
            q_acc = fma(q_state[(ulong)w * projection + channel],
                        q_conv[(ulong)channel * 4u + w], q_acc);
            k_acc = fma(k_state[(ulong)w * projection + channel],
                        k_conv[(ulong)channel * 4u + w], k_acc);
            v_acc = fma(v_state[(ulong)w * projection + channel],
                        v_conv[(ulong)channel * 4u + w], v_acc);
        }
        const float q_new = q[index];
        const float k_new = k[index];
        const float v_new = v[index];
        q_acc = fma(q_new, q_conv[(ulong)channel * 4u + 3u], q_acc);
        k_acc = fma(k_new, k_conv[(ulong)channel * 4u + 3u], k_acc);
        v_acc = fma(v_new, v_conv[(ulong)channel * 4u + 3u], v_acc);
        q_state[channel] = q_state[projection + channel];
        q_state[projection + channel] = q_state[2ul * projection + channel];
        q_state[2ul * projection + channel] = q_new;
        k_state[channel] = k_state[projection + channel];
        k_state[projection + channel] = k_state[2ul * projection + channel];
        k_state[2ul * projection + channel] = k_new;
        v_state[channel] = v_state[projection + channel];
        v_state[projection + channel] = v_state[2ul * projection + channel];
        v_state[2ul * projection + channel] = v_new;

        sq[tid] = q_acc / (1.0f + exp(-q_acc));
        sk[tid] = k_acc / (1.0f + exp(-k_acc));
        v[index] = v_acc / (1.0f + exp(-v_acc));
        const float gate = raw_gate[index] + dt_bias[channel];
        raw_gate[index] = exp(args.lower_bound *
            (1.0f / (1.0f + exp(-exp(a_log[head]) * gate))));
        threadgroup_barrier(mem_flags::mem_threadgroup |
                           mem_flags::mem_device);

        float q_sumsq = simd_sum(sq[tid] * sq[tid]);
        float k_sumsq = simd_sum(sk[tid] * sk[tid]);
        if (lane == 0u) {
            reduce_q[sg] = q_sumsq;
            reduce_k[sg] = k_sumsq;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float q_total = lane < 4u ? reduce_q[lane] : 0.0f;
        float k_total = lane < 4u ? reduce_k[lane] : 0.0f;
        q_total = simd_sum(q_total);
        k_total = simd_sum(k_total);
        q[index] = sq[tid] * rsqrt(q_total + 1.0e-6f) *
                   0x1.6a09e6p-4f;
        k[index] = sk[tid] * rsqrt(k_total + 1.0e-6f);
        threadgroup_barrier(mem_flags::mem_threadgroup |
                           mem_flags::mem_device);
    }
}

kernel void kernel_glm53_kda_prefill_recurrence(
        constant glm53_kda_args &args,
        device const float   *q,
        device const float   *k,
        device const float   *v,
        device const float   *decay,
        device const float   *raw_beta,
        device float         *state,
        device float         *out,
        uint2 tgpig [[threadgroup_position_in_grid]],
        ushort lane [[thread_index_in_simdgroup]],
        ushort sg [[simdgroup_index_in_threadgroup]]) {
    constexpr uint D = 128u;
    const uint head = tgpig.x;
    const uint value = tgpig.y * 4u + sg;
    if (head >= args.n_heads || value >= D) return;
    const uint projection = args.n_heads * D;
    const uint k0 = lane * 4u;
    device float4 *state_ptr = (device float4 *)(
        state + ((ulong)head * D + value) * D + k0);
    float4 h = *state_ptr;

    for (uint token = 0; token < args.n_rows; token++) {
        const ulong base = (ulong)token * projection + head * D;
        const float4 q4 = *((device const float4 *)(q + base + k0));
        const float4 k4 = *((device const float4 *)(k + base + k0));
        const float4 decay4 =
            *((device const float4 *)(decay + base + k0));
        h *= decay4;
        const float hk = simd_sum(dot(h, k4));
        const float beta = 1.0f /
            (1.0f + exp(-raw_beta[(ulong)token * args.n_heads + head]));
        const float delta_v = (v[base + value] - hk) * beta;
        h = fma(k4, float4(delta_v), h);
        const float result = simd_sum(dot(h, q4));
        if (lane == 0u) out[base + value] = result;
    }
    *state_ptr = h;
}

kernel void kernel_glm53_kda_prefill_output(
        constant glm53_kda_args &args,
        device float         *out,
        device const float   *output_gate,
        device const float   *output_norm,
        threadgroup float    *partial [[threadgroup(0)]],
        uint2 tgpig [[threadgroup_position_in_grid]],
        ushort tid [[thread_index_in_threadgroup]],
        ushort lane [[thread_index_in_simdgroup]],
        ushort sg [[simdgroup_index_in_threadgroup]]) {
    constexpr uint D = 128u;
    const uint token = tgpig.x;
    const uint head = tgpig.y;
    if (token >= args.n_rows || head >= args.n_heads) return;
    const uint projection = args.n_heads * D;
    const ulong base = (ulong)token * projection + head * D;
    const float raw = out[base + tid];
    float sumsq = simd_sum(raw * raw);
    if (lane == 0u) partial[sg] = sumsq;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float total = lane < 4u ? partial[lane] : 0.0f;
    total = simd_sum(total);
    const float scale = rsqrt(total / (float)D + args.norm_eps);
    out[base + tid] = raw * scale * output_norm[tid] /
        (1.0f + exp(-output_gate[base + tid]));
}
"""####,
####"""
// GLM 5.3 operations. Pooling ported from GiorgioOppo/ds4
// acf5c16bb6a01f8c4f027a0db265ae270d8907ab (MIT).
// Concatenate after glm52_quant, glm53_bf16, and the shared dense kernels.
struct ds4_metal_args_glm53_indexer_pool_update {
    uint n_tokens, pos0, cache_cap, head_dim, pool_size, cache_f16;
    float eps;
};
static inline float glm53_pool_bf16_to_f32(ushort value) {
    return as_type<float>((uint)value << 16);
}

kernel void kernel_glm53_indexer_pool_update(
        constant ds4_metal_args_glm53_indexer_pool_update &args,
        device const char   *raw_k,
        device const char   *gate,
        device const float  *norm_weight,
        device const float  *norm_bias,
        device const ushort *ape,
        device       char   *pool_cache,
        device       float  *tail_k,
        device       float  *tail_gate,
        threadgroup  float  *shared [[threadgroup(0)]],
        uint tid [[thread_index_in_threadgroup]],
        uint3 tgpig [[threadgroup_position_in_grid]]) {
    if (args.head_dim == 0u || args.pool_size == 0u ||
        tid >= args.head_dim || args.n_tokens == 0u) return;

    const uint pool = args.pos0 / args.pool_size + tgpig.x;
    const uint pool_start = pool * args.pool_size;
    const uint input_end = args.pos0 + args.n_tokens;
    if (pool_start >= input_end || pool_start + args.pool_size <= args.pos0) return;

    threadgroup float *rows = shared;
    threadgroup float *mean = rows + args.pool_size * args.head_dim;
    threadgroup float *inv = mean + args.pool_size;
    const bool complete = pool_start + args.pool_size <= input_end;

    for (uint r = 0; r < args.pool_size; r++) {
        const uint pos = pool_start + r;
        float k_value = 0.0f;
        float gate_value = 0.0f;
        if (pos >= args.pos0 && pos < input_end) {
            const uint src_row = pos - args.pos0;
            k_value = ((device const float *)raw_k)[
                (uint64_t)src_row * args.head_dim + tid];
            gate_value = ((device const float *)gate)[
                (uint64_t)src_row * args.head_dim + tid];
            if (!complete) {
                tail_k[(uint64_t)r * args.head_dim + tid] = k_value;
                tail_gate[(uint64_t)r * args.head_dim + tid] = gate_value;
            }
        } else {
            k_value = tail_k[(uint64_t)r * args.head_dim + tid];
            gate_value = tail_gate[(uint64_t)r * args.head_dim + tid];
        }
        rows[(uint64_t)r * args.head_dim + tid] = k_value;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    if (!complete || pool >= (args.cache_cap + args.pool_size - 1u) / args.pool_size) {
        return;
    }

    if (tid < args.pool_size) {
        const uint r = tid;
        float sum = 0.0f;
        for (uint d = 0; d < args.head_dim; d++) {
            sum += rows[(uint64_t)r * args.head_dim + d];
        }
        const float m = sum / (float)args.head_dim;
        float ss = 0.0f;
        for (uint d = 0; d < args.head_dim; d++) {
            const float delta = rows[(uint64_t)r * args.head_dim + d] - m;
            ss += delta * delta;
        }
        mean[r] = m;
        inv[r] = rsqrt(ss / (float)args.head_dim + args.eps);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    float max_logit = -INFINITY;
    float logits[4];
    for (uint r = 0; r < args.pool_size; r++) {
        const uint pos = pool_start + r;
        float gate_value;
        if (pos >= args.pos0) {
            const uint src_row = pos - args.pos0;
            gate_value = ((device const float *)gate)[
                (uint64_t)src_row * args.head_dim + tid];
        } else {
            gate_value = tail_gate[(uint64_t)r * args.head_dim + tid];
        }
        logits[r] = gate_value +
            glm53_pool_bf16_to_f32(ape[(uint64_t)r * args.head_dim + tid]);
        max_logit = max(max_logit, logits[r]);
    }

    float denom = 0.0f;
    for (uint r = 0; r < args.pool_size; r++) {
        logits[r] = exp(logits[r] - max_logit);
        denom += logits[r];
    }
    float pooled = 0.0f;
    for (uint r = 0; r < args.pool_size; r++) {
        const float normalized =
            (rows[(uint64_t)r * args.head_dim + tid] - mean[r]) * inv[r] *
            norm_weight[tid] + norm_bias[tid];
        pooled += (logits[r] / denom) * normalized;
    }

    const uint64_t dst_index = (uint64_t)pool * args.head_dim + tid;
    if (args.cache_f16 != 0u) {
        ((device half *)pool_cache)[dst_index] = (half)pooled;
    } else {
        ((device float *)pool_cache)[dst_index] = pooled;
    }
}


struct glm53_projection_args { uint type, input, output, rows, heads, row_bytes; };
static inline float glm53_dot_lane(uint type, device const uchar *w,
                                  device const float *x, uint n, uint lane) {
    float sum = 0;
    if (type == 0u || type == 1u || type == 30u) {
        for (uint k = lane; k < n; k += 32u) {
            const float v = type == 0u ? ((device const float *)w)[k] :
                type == 1u ? float(((device const half *)w)[k]) :
                glm53_bf16_to_f32(((device const ushort *)w)[k]);
            sum = fma(v, x[k], sum);
        }
    } else {
        for (uint k = lane; k < n / 32u; k += 32u)
            sum += glm52_dot_kquant_group(type, w, x, k);
    }
    return simd_sum(sum);
}
kernel void kernel_glm53_grouped_projection(
    constant glm53_projection_args &a, device const uchar *w,
    device const float *x, device float *out,
    uint3 g [[threadgroup_position_in_grid]],
    ushort lane [[thread_index_in_simdgroup]], ushort sg [[simdgroup_index_in_threadgroup]]) {
    const uint row = g.x * 4u + sg;
    if (row >= a.output || g.y >= a.rows || g.z >= a.heads) return;
    float sum = glm53_dot_lane(a.type, w + ((ulong)g.z * a.output + row) * a.row_bytes,
        x + ((ulong)g.y * a.heads + g.z) * a.input, a.input, lane);
    if (lane == 0u) out[((ulong)g.y * a.heads + g.z) * a.output + row] = sum;
}

static inline float glm53_weight_value(device const uchar *row, uint type, uint k) {
    if (type == 0u) return ((device const float *)row)[k];
    if (type == 1u) return float(((device const half *)row)[k]);
    if (type == 30u) return glm53_bf16_to_f32(((device const ushort *)row)[k]);
    if (type == 8u) {
        device const uchar *b = row + (k / 32u) * 34u;
        return glm52_half_at(b) * float(((device const char *)(b + 2))[k % 32u]);
    }
    device const uchar *b = row + (k / 256u) * 144u;
    const uint j = (k % 256u) / 32u;
    const uchar2 sm = glm52_scale_min_k4(j, b + 4);
    const uchar packed = b[16u + (j / 2u) * 32u + k % 32u];
    const uint q = j % 2u == 0u ? packed & 15u : packed >> 4u;
    return glm52_half_at(b) * float(sm.x) * float(q) - glm52_half_at(b + 2) * float(sm.y);
}
kernel void kernel_glm53_embedding_hc(constant glm53_projection_args &a,
    device const uchar *w, device const int *ids, device float *out,
    uint2 gid [[thread_position_in_grid]]) {
    if (gid.x >= a.input || gid.y >= a.rows) return;
    const float v = glm53_weight_value(w + (ulong)ids[gid.y] * a.row_bytes, a.type, gid.x);
    for (uint h = 0; h < 4; h++) out[((ulong)gid.y * 4 + h) * a.input + gid.x] = v;
}

kernel void kernel_glm53_route(constant uint &rows, device const float *logits,
    device const float *bias, device uint *ids, device float *weights,
    uint token [[thread_position_in_grid]]) {
    if (token >= rows) return;
    float probabilities[288], scores[288];
    for (uint i=0; i<288; i++) {
        probabilities[i] = 1.0f / (1.0f + exp(-logits[token*288+i]));
        scores[i] = probabilities[i] + bias[i];
    }
    float sum=0;
    for (uint slot=0; slot<8; slot++) {
        uint best=0; float score=-INFINITY;
        for (uint i=0; i<288; i++) if (scores[i]>score) { score=scores[i]; best=i; }
        ids[token*8+slot]=best; weights[token*8+slot]=probabilities[best];
        sum+=probabilities[best]; scores[best]=-INFINITY;
    }
    for (uint slot=0; slot<8; slot++) weights[token*8+slot]*=2.5f/max(sum,1e-20f);
}

// Applications of one expert are gathered to make a real batched projection;
// scatter is collision-free within an expert, with dispatches ordered by graph.
struct glm53_rows_args { uint width, rows; float scale; };
kernel void kernel_glm53_gather_rows(constant glm53_rows_args &a,
    device const float *src, device const uint *ids, device float *out,
    uint2 gid [[thread_position_in_grid]]) {
    if(gid.x<a.width && gid.y<a.rows) out[(ulong)gid.y*a.width+gid.x]=src[(ulong)ids[gid.y]*a.width+gid.x];
}
kernel void kernel_glm53_scatter_add(constant glm53_rows_args &a,
    device const float *src, device const uint *ids, device float *out,
    uint2 gid [[thread_position_in_grid]]) {
    if(gid.x<a.width && gid.y<a.rows) out[(ulong)ids[gid.y]*a.width+gid.x]+=src[(ulong)gid.y*a.width+gid.x];
}
kernel void kernel_glm53_swiglu_route(constant glm53_rows_args &a,
    device const float *gate, device const float *up, device const float *routes,
    device float *out, uint2 gid [[thread_position_in_grid]]) {
    if(gid.x>=a.width || gid.y>=a.rows) return;
    const ulong i=(ulong)gid.y*a.width+gid.x;
    const float g=min(gate[i],a.scale), u=clamp(up[i],-a.scale,a.scale);
    out[i]=(g/(1.0f+exp(-g)))*u*routes[gid.y];
}

struct glm53_index_args { uint visible, selected, heads; float scale; };
kernel void kernel_glm53_index_scores(constant glm53_index_args &a,
    device const float *q, device const float *weights, device const half *cache,
    device float *scores, uint pool [[threadgroup_position_in_grid]],
    ushort lane [[thread_index_in_simdgroup]]) {
    if(pool>=a.visible) return;
    float score=0;
    for(uint h=0;h<a.heads;h++) {
        float dot=0;
        for(uint d=lane;d<128;d+=32) dot=fma(q[h*128+d],float(cache[(ulong)pool*128+d]),dot);
        dot=simd_sum(dot);
        score+=max(dot*a.scale,0.0f)*weights[h];
    }
    if(lane==0) scores[pool]=score;
}
kernel void kernel_glm53_select_raw(constant glm53_index_args &a,
    device const uint *pools, device uint *out, uint i [[thread_position_in_grid]]) {
    if(i>=a.selected) return;
    uint v=i;
    if(a.visible>2048u) {
        if(i<2048u) v=pools[i/4u]*4u+i%4u;
        else v=a.visible-a.visible%4u+(i-2048u);
    }
    out[i]=v<a.visible ? v:0xffffffffu;
}

// Absorbed MLA: every SIMD group scores one selected latent row, then the
// threadgroup accumulates the stable softmax in the 512-dimensional cache.
kernel void kernel_glm53_attention(constant glm53_index_args &a,
    device const float *q, device const half *cache, device const uint *selected,
    device float *out, threadgroup float *shared [[threadgroup(0)]],
    uint head [[threadgroup_position_in_grid]], ushort tid [[thread_index_in_threadgroup]],
    ushort lane [[thread_index_in_simdgroup]], ushort sg [[simdgroup_index_in_threadgroup]]) {
    threadgroup float *scores=shared, *red=shared+a.selected;
    for(uint s=sg;s<a.selected;s+=4u) {
        const uint row=selected[s]; float dot=0;
        if(row<a.visible) for(uint d=lane;d<512;d+=32)
            dot=fma(q[head*512+d],float(cache[(ulong)row*512+d]),dot);
        dot=simd_sum(dot);
        if(lane==0) scores[s]=row<a.visible ? dot*a.scale:-INFINITY;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float m=-INFINITY;
    for(uint s=tid;s<a.selected;s+=128) m=max(m,scores[s]);
    m=simd_max(m); if(lane==0) red[sg]=m;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    m=max(max(red[0],red[1]),max(red[2],red[3]));
    float denom=0;
    for(uint s=tid;s<a.selected;s+=128) { float v=exp(scores[s]-m); scores[s]=v; denom+=v; }
    denom=simd_sum(denom); if(lane==0) red[sg]=denom;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    denom=max(red[0]+red[1]+red[2]+red[3],1e-20f);
    for(uint d=tid;d<512;d+=128) {
        float v=0;
        for(uint s=0;s<a.selected;s++) if(selected[s]<a.visible)
            v=fma(scores[s],float(cache[(ulong)selected[s]*512+d]),v);
        out[head*512+d]=v/denom;
    }
}

kernel void kernel_glm53_store_half(constant uint &count, device const float *src,
    device half *dst, uint i [[thread_position_in_grid]]) {
    if(i<count) dst[i]=half(src[i]);
}

kernel void kernel_glm53_scatter_contribution(constant glm53_rows_args &a,
    device const float *src, device const uint *slots, device float *out,
    uint2 gid [[thread_position_in_grid]]) {
    if(gid.x<a.width && gid.y<a.rows) out[(ulong)slots[gid.y]*a.width+gid.x]=src[(ulong)gid.y*a.width+gid.x];
}
kernel void kernel_glm53_combine_experts(constant glm53_rows_args &a,
    device const float *contributions, device float *shared_out,
    uint2 gid [[thread_position_in_grid]]) {
    if(gid.x>=a.width || gid.y>=a.rows) return;
    float sum=0;
    for(uint k=0;k<8;k++) sum+=contributions[((ulong)gid.y*8+k)*a.width+gid.x];
    shared_out[(ulong)gid.y*a.width+gid.x]+=sum;
}
"""####
]
}
