#!/usr/bin/env python3
"""Embed native backend shaders without changing the legacy Metal library.

Each family compiles only when selected. metal/ remains the source of truth;
this keeps SwiftPM and shipped app bundles independent of the checkout path.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def literal(paths):
    text = "\n".join((ROOT / path).read_text() for path in paths)
    return '####"""\n' + text.rstrip("\n") + '\n"""####'


def emit(family, name, properties):
    path = ROOT / "Sources/DS4Metal/Backends" / family / (name + ".swift")
    body = "// Generated by scripts/embed_backend_kernels.py; edit metal/ sources.\n"
    body += "enum " + name + " {\n"
    for key, value in properties:
        body += "    static let " + key + " = " + value + "\n"
    body += "}\n"
    path.write_text(body)
    print("wrote", path.relative_to(ROOT))


emit("Bonsai", "BonsaiMetalSource", [
    ("source", literal(["metal/bonsai/bonsai.metal"]))])
emit("Qwen38", "Qwen38KernelSource", [
    ("source", literal(["metal/qwen38/prelude.metal", "metal/qwen38/qwen4.metal",
                        "metal/qwen38/swift_bridge.metal"]))])
emit("GLM53", "GLM53KernelSources", [
    ("all: [String]", "[\n" + ",\n".join(literal(["metal/glm53/" + name + ".metal"])
        for name in ("glm53_bf16", "glm53_kda", "glm53_ops")) + "\n]")])
emit("DeepSeek41", "DeepSeek41MetalSource", [
    ("source", literal(["metal/deepseek41/dsv41.metal"])),
    ("graph", literal(["metal/deepseek41/swift_graph.metal"]))])
