import Foundation

extension HuggingFaceSource {
    public static let glm53Full = Self(repository: "antirez/glm-5.3-gguf",
        revision: "1434dad1a25c6318c9befef38d7735a1e0e15f1d")
    public static let qwen38Encoder = Self(repository: "ggml-org/Qwen3.8-Flash-Next-GGUF",
        revision: "01534bc2e1877d5de995b73d247d4459d273e688")
}

/// Explicitly downloadable references and sidecars, excluded from model choices.
public enum NativeModelAccessoryCatalog {
    public static let entries: [ModelCatalogEntry] = [
        .init(id: .glm53FullIQ2, displayName: "GLM 5.3 completo · IQ2_XXS", profile: .glm53Full,
              summary: "Checkpoint GLM 5.3 completo, distinto da GLM 5.3 Flash. Solo download: questa integrazione aggiunge il decoder Flash e non abilita il checkpoint completo.",
              artifacts: [.init(id: ModelCatalogID.glm53FullIQ2.rawValue,
                  file: "GLM-5.3-UD-IQ2_XXS_RoutedIQ2XXS_blk78Q2K.gguf", approxGB: 211,
                  note: "GLM 5.3 completo · solo download",
                  sha256: "059b36accd4c9acf73099da9f703b574d627869d619b7c4c316aa856e33d472e",
                  expectedSizeBytes: 211_075_860_864, source: .glm53Full)],
              runtimeAvailability: .downloadOnly(reason: "Il checkpoint GLM 5.3 completo non è abilitato; usa GLM 5.3 Flash per la nuova integrazione.")),
        .init(id: .bonsai2F16, displayName: "Ternary Bonsai 2 27B · F16", profile: .bonsai2,
              summary: "F16 di riferimento, solo download. Il decoder Bonsai di questa versione richiede pesi ternari folded PQ2_0/PTQ1_0.",
              artifacts: [.init(id: ModelCatalogID.bonsai2F16.rawValue, file: "Ternary-Bonsai-2-27B-F16.gguf",
                  approxGB: 54, note: "Solo download",
                  sha256: "f6f3b2c9b41956c34b379ec7c301dc936bc38d79b3c24c83388dd7d76000c180", expectedSizeBytes: 53808408928,
                  role: .mainModel, source: .bonsai2)],
              runtimeAvailability: .downloadOnly(reason: "F16 di riferimento, solo download. Il decoder Bonsai di questa versione richiede pesi ternari folded PQ2_0/PTQ1_0.")),
        .init(id: .glm53FP8, displayName: "GLM 5.3 Flash · FP8", profile: .glm53,
              summary: "Checkpoint FP8, solo download. Il decoder Swift non implementa questa codifica; seleziona Q2 oppure Q4_K per la chat.",
              artifacts: [.init(id: ModelCatalogID.glm53FP8.rawValue, file: "GLM-5.3-Flash-FP8.gguf",
                  approxGB: 327, note: "Solo download",
                  sha256: "59275e79a5246835226230616b3865fb599c661f242c38316b1cf82869bd14c9", expectedSizeBytes: 327209059584,
                  role: .mainModel, source: .glm53)],
              runtimeAvailability: .downloadOnly(reason: "Checkpoint FP8, solo download. Il decoder Swift non implementa questa codifica; seleziona Q2 oppure Q4_K per la chat.")),
        .init(id: .bonsai2VisionBF16, displayName: "Bonsai 2 · encoder immagini BF16", profile: .bonsai2,
              summary: "Encoder Bonsai BF16. Solo download: la comprensione immagini Bonsai non è ancora implementata in questa versione.",
              artifacts: [.init(id: ModelCatalogID.bonsai2VisionBF16.rawValue, file: "Ternary-Bonsai-2-27B-mmproj-BF16.gguf",
                  approxGB: 1, note: "Solo download",
                  sha256: "e287342d92332fa3577ed1d42e921dac9370c08da58ba9337fa450f6cc76cfd7", expectedSizeBytes: 931145856,
                  role: .optionalComponent, source: .bonsai2)],
              runtimeAvailability: .downloadOnly(reason: "Encoder Bonsai BF16. Solo download: la comprensione immagini Bonsai non è ancora implementata in questa versione.")),
        .init(id: .bonsai2VisionQ8, displayName: "Bonsai 2 · encoder immagini Q8_0", profile: .bonsai2,
              summary: "Encoder Bonsai Q8_0. Solo download: richiede il modello Bonsai e una futura integrazione immagini.",
              artifacts: [.init(id: ModelCatalogID.bonsai2VisionQ8.rawValue, file: "Ternary-Bonsai-2-27B-mmproj-Q8_0.gguf",
                  approxGB: 1, note: "Solo download",
                  sha256: "6807ede61d570bb86ba34b756a0fa109edc33668604de867c6ea6d8f1d631903", expectedSizeBytes: 629246976,
                  role: .optionalComponent, source: .bonsai2)],
              runtimeAvailability: .downloadOnly(reason: "Encoder Bonsai Q8_0. Solo download: richiede il modello Bonsai e una futura integrazione immagini.")),
        .init(id: .qwen38VisionQ8, displayName: "Qwen 3.8 Flash Next · encoder immagini Q8_0", profile: .qwen38,
              summary: "Encoder ufficiale ggml-org. Solo download: la comprensione immagini Qwen non è ancora implementata in questa versione.",
              artifacts: [.init(id: ModelCatalogID.qwen38VisionQ8.rawValue, file: "mmproj-Qwen3.8-Flash-Next-Q8_0.gguf",
                  approxGB: 1, note: "Solo download",
                  sha256: "b2e9b5e4a44c107f8867e67dbf09b607fd99ae33c1a97a60a6720aeb252a9dad", expectedSizeBytes: 616703104,
                  role: .optionalComponent, source: .qwen38Encoder)],
              runtimeAvailability: .downloadOnly(reason: "Encoder ufficiale ggml-org. Solo download: la comprensione immagini Qwen non è ancora implementata in questa versione.")),
        .init(id: .deepSeek41Vision, displayName: "DeepSeek V4.1 Flash · encoder immagini", profile: .deepSeek41,
              summary: "Encoder specifico V4.1, diverso da Vision-Exp V4. Solo download: non utilizzabile con il runtime immagini V4.",
              artifacts: [.init(id: ModelCatalogID.deepSeek41Vision.rawValue, file: "DeepSeek-V4.1-Flash-Vision.gguf",
                  approxGB: 1, note: "Solo download",
                  sha256: "cc283f032b3e8b8d78aeb5fccaa14e97b859b0c53aae3cd6bffa690ddf0e9e15", expectedSizeBytes: 970555552,
                  role: .optionalComponent, source: .deepSeek41)],
              runtimeAvailability: .downloadOnly(reason: "Encoder specifico V4.1, diverso da Vision-Exp V4. Solo download: non utilizzabile con il runtime immagini V4.")),
        .init(id: .glm53Vision, displayName: "GLM 5.3 Flash · encoder immagini", profile: .glm53,
              summary: "Encoder specifico GLM 5.3 Flash. Solo download: la comprensione immagini GLM non è ancora implementata in questa versione.",
              artifacts: [.init(id: ModelCatalogID.glm53Vision.rawValue, file: "GLM-5.3-Flash-Vision-Encoder.gguf",
                  approxGB: 1, note: "Solo download",
                  sha256: "ae23e14c6979e889051b2e4a39351abcdafb161e18e606fae4d8c40095a4bf3a", expectedSizeBytes: 1127280960,
                  role: .optionalComponent, source: .glm53)],
              runtimeAvailability: .downloadOnly(reason: "Encoder specifico GLM 5.3 Flash. Solo download: la comprensione immagini GLM non è ancora implementata in questa versione.")),
    ]
}
